export type DeviceType =
  | 'wide-angle'
  | 'ultra-wide-angle'
  | 'telephoto'
  | 'dual'
  | 'dual-wide'
  | 'triple'
  | 'quad'
  | 'continuity'
  | 'lidar-depth'
  | 'true-depth'
  | 'time-of-flight-depth'
  | 'external'
  | 'unknown'
