version: 2

updates:
  - package-ecosystem: "gradle"
    directories:
      - "/apps/simple-camera/android/"
      - "/packages/react-native-vision-camera/android/"
      - "/packages/react-native-vision-camera-barcode-scanner/android/"
      - "/packages/react-native-vision-camera-location/android/"
      - "/packages/react-native-vision-camera-resizer/android/"
    schedule:
      interval: "daily"
    groups:
      camera-libs:
        patterns:
          - "androidx.camera:*"
      gms-location:
        patterns:
          - "com.google.android.gms:play-services-location"
      mlkit:
        patterns:
          - "com.google.mlkit:*"
          - "com.google.android.gms:play-services-mlkit-*"
      gradle-build-and-plugins:
        patterns:
          - "*"
        exclude-patterns:
          - "androidx.camera:*"
          - "com.google.android.gms:play-services-location"
          - "com.google.mlkit:*"
          - "com.google.android.gms:play-services-mlkit-*"
