source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.4.9"

# Exclude problematic versions of cocoapods and activesupport that cause build failures.
gem 'cocoapods', '>= 1.16.2', '< 1.17'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '>= 1.27.0', '< 2.0'
gem 'concurrent-ruby', '>= 1.3.6', '< 2.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
