require 'cocoapods'
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


  platform :ios, 14.5
prepare_react_native_project!

flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'VisionCameraExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'VisionCamera', :path => '../..'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Enable or disable our Example FP Plugins depending on FPs are enabled or not.
    # In CI, we disable FPs to test if everything builds without FPs, so we also need to
    # disable the FP plugins there.
    podspec_path = File.join(__dir__, '../../VisionCamera.podspec')
    podspec = Pod::Specification.from_file(podspec_path)
    enableFrameProcessors = false
    begin
      podspec.subspec_by_name('VisionCamera/FrameProcessors')
      Pod::UI.puts "Frame Processors are enabled."
      enableFrameProcessors = true
    rescue => e
      Pod::UI.puts "Frame Processors are not enabled."
      enableFrameProcessors = false
    end
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] ||= ''
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] << ' VISION_CAMERA_ENABLE_FRAME_PROCESSORS'
        end
      end
    end
  end
end
